Document: freshplayerplugin
Title: Debian freshplayerplugin Manual
Author: <insert document author here>
Abstract: This manual describes what freshplayerplugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freshplayerplugin/freshplayerplugin.sgml.gz

Format: postscript
Files: /usr/share/doc/freshplayerplugin/freshplayerplugin.ps.gz

Format: text
Files: /usr/share/doc/freshplayerplugin/freshplayerplugin.text.gz

Format: HTML
Index: /usr/share/doc/freshplayerplugin/html/index.html
Files: /usr/share/doc/freshplayerplugin/html/*.html
